### ISSUE TITLE
[Feature request] dynamic inventory : veyon-ctl networkobjects update

### ISSUE THREAD

**Issue by eoli3n** [veyon/veyon#373]
I configure veyon with veyton-ctl through ansible.
Problem is that at each ansible run, i run the ``networkobjects import`` with veyon-ctl, it creates nodes which already exists.

Could be great to be able to update nodes, based on mac address as primary key with ``veyon-ctl networkobjects update``

example : 
``test.csv``
```
Room1;Node1;162.168.0.1;00:00:00:00:00:01
Room2;Node1;192.168.0.1;00:00:00:00:00:01
Room2;Node2;192.168.1.1;FF:FF:FF:FF:FF:01
```

add '-c' option as 'check is already exists
```
root@bionic:~# veyon-ctl networkobjects import test.csv format "%room%;%name%;%host%;%mac%"
[OK]
root@bionic:~# veyon-ctl networkobjects list
Salle "Room1"
	Ordinateur "Node1" (adresse hôte: "162.168.0.1" adresse MAC: "00:00:00:00:00:01")
Salle "Room2"
	Ordinateur "Node1" (adresse hôte: "192.168.0.1" adresse MAC: "00:00:00:00:00:01")
	Ordinateur "Node2" (adresse hôte: "192.168.1.1" adresse MAC: "FF:FF:FF:FF:FF:01")
```

Then update without modification
```
root@bionic:~# veyon-ctl networkobjects update test.csv format "%room%;%name%;%host%;%mac%"
[Nothing to do]
```

Then modification of CSV, changed Node1 IP adress, and renamed Room2 node
``test.csv``
```
Room1;Node1;162.168.0.230;00:00:00:00:00:01
Room2;Node1;192.168.0.230;00:00:00:00:00:01
Room2;Node4;192.168.1.1;FF:FF:FF:FF:FF:01
```

```
root@bionic:~# veyon-ctl networkobjects update test.csv format "%room%;%name%;%host%;%mac%"
[OK]
root@bionic:~# veyon-ctl networkobjects list
Salle "Room1"
	Ordinateur "Node1" (adresse hôte: "162.168.0.230" adresse MAC: "00:00:00:00:00:01")
Salle "Room2"
	Ordinateur "Node1" (adresse hôte: "192.168.0.230" adresse MAC: "00:00:00:00:00:01")
	Ordinateur "Node4" (adresse hôte: "192.168.1.1" adresse MAC: "FF:FF:FF:FF:FF:01")
```

For now, i can't ``clear;import`` at each run because it will probably break Veyon if ansible runs during Veyon usage.

**Comment by eoli3n** [comment]
BTW, it could be cool to have a Ubuntu PPA to install veyon...
For posterity, here's my ansible role, to install and configure veyon

```
---
- name: Install x11vnc
  apt: name=x11vnc state=present

- name: Check veyon install
  shell: dpkg-query -W veyon
  register: veyon_check
  ignore_errors: True

- name: Copy veyon installer
  copy: src=files/veyon_4.0.92-ubuntu-bionic_amd64.deb dest=/tmp/
  when: veyon_check is failed

- name: Install veyon
  apt: deb=/tmp/veyon_4.0.92-ubuntu-bionic_amd64.deb
  when: veyon_check is failed
  notify:
    - restart veyon

- name: Create veyon config dir
  file: path=/etc/veyon state=directory

- name: Copy Veyon Classrooms
  copy: src=files/test.csv dest=/etc/veyon/
  register: classrooms

- name: Clear Veyon Classrooms
  shell: veyon-ctl networkobjects clear
  when: classrooms.changed

- name: Import Veyon Classrooms
  shell: veyon-ctl networkobjects import /etc/veyon/test.csv format "%room%;%name%;%host%;%mac%"
  when: classrooms.changed
  notify:
    - restart veyon

- name: Copy Veyon Configuration
  copy: src=files/veyon.conf dest=/etc/veyon/
  register: veyonconf

- name: Import Veyon Configuration
  shell: veyon-ctl config import /etc/veyon/veyon.conf
  when: veyonconf.changed
  notify:
    - restart veyon
```
